### ISSUE TITLE
Add option for printing date and Time on tickets.

### ISSUE THREAD

**Issue by atclarkson** [ATC-Industries/hotspotPrinter#9]
Can use checkbox4 probably

**Comment by agritron** [comment]
I think always print date and time , one less option user has to make a decision on. Save checkbox for another option. 
Do we want to print our name on every ticket?

**Comment by atclarkson** [comment]
That's funny I was actually thinking the same thing it's kind of an obvious choice really...  unless they can't figure out how to set the date time

We could have a flag that on first burn it says "dontPrintDate" and then after the first time they set the time it flips that flag.

Yes we should print something like "Official weight by Pro Tournament Scales..... or Pro Tournament Systems....

**Comment by agritron** [comment]
I like that touch. Good idea, I will add a flag to not print date and time illness it has been set by the user.  But wait, What if they get it and the time date is correct for their time zone. They won’t reset it and it won’t print.  This might cause confusion to the user.

**Comment by agritron** [comment]
I will add our name to the ticket printout.

**Comment by atclarkson** [comment]
Done.  Added RTC chip.
